### ISSUE TITLE
SyntaxError: Use of const in strict mode.

### ISSUE THREAD

**Issue by brianmingus** [sindresorhus/emoj#1]
$ emoj 'i love unicorns'
/home/mingus/.nvm/versions/node/v0.12.7/lib/node_modules/emoj/cli.js:3
const readline = require('readline');
^^^^^
SyntaxError: Use of const in strict mode.
    at exports.runInThisContext (vm.js:73:16)
    at Module._compile (module.js:443:25)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
    at startup (node.js:129:16)
    at node.js:814:3

**Comment by sindresorhus** [comment]
This is clearly documented in the readme:

> Ensure you have Node.js **version 4** or higher installed.

**Comment by brianmingus** [comment]
$ nodejs --version
v4.2.6

**Comment by sindresorhus** [comment]
From your error:

> /home/mingus/.nvm/versions/node/v0.12.7/lib/node_modules/emoj/cli.js:3
